server:
  port: 8002
spring:
  application:
    name: user-server
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?user=root&password=&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: select 1 from dual
      ##validation-query-timeout:
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 300000
      ##max-evictable-idle-time-millis:
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 28
    jdbc-type-for-null: 'null'
  type-aliases-package: com.spring.user.server.entity
  mapper-locations: classpath:/sqlmapper/*.xml
  global-config:
    banner: false
